### PR TITLE
Fix duplicate reminder delivery loop under database load

### LINKED ISSUE #73: Duplicate reminder delivery loop when database is slow or overloaded
## Summary

When a large batch of reminders become due simultaneously and the backing database is under heavy load, reminders can enter an infinite re-delivery loop. The reminders are delivered via fire-and-forget `Tell` but never marked as completed in the database, causing them to be re-fetched and re-delivered on every subsequent processing tick (~every 5 seconds).

## Root Cause

`ProcessReminders` in `ReminderScheduler.cs` creates a single `CancellationTokenSource` with `StorageTimeout` (default 5s) that is shared across the entire processing pipeline:

1. `GetNextRemindersAsync` - fetch due reminders
2. Deliver each reminder via `Tell` (fire-and-forget, immediate)
3. `MarkRemindersAsCompletedAsync` - mark delivered reminders as completed
4. `ScheduleReminderAsync` - reschedule retries/recurring
5. `GetRemindersOverviewAsync` - reload the overview

When a large number of reminders are due at once, step 1 can consume most of the timeout budget (deserializing many rows from an already-stressed database). By the time step 3 runs, the `CancellationToken` has expired. The SQL implementation catches the `OperationCanceledException` and returns `false` — but the reminders have already been delivered in step 2.

On the next timer tick, `GetNextRemindersAsync` finds the same reminders still marked as incomplete (`IsCompleted = 0`) and delivers them again. This creates a tight loop where the same reminders are delivered repeatedly every few seconds, further stressing the database and preventing it from ever recovering enough to complete the mark-as-completed operation.

## Observed Behavior (User Report)

- ~2,000 non-recurring reminders scheduled for the same time
- All reminders fired at the scheduled time (correct)
- Reminders continued to be re-delivered approximately every 5 seconds indefinitely
- Database DTU% hit 100% during the incident
- Only resolved by manually clearing reminders from the database

## Contributing Factors

1. **Single CTS for entire pipeline**: The timeout budget is shared between fetch, deliver, mark-complete, and reschedule operations. A slow fetch leaves no budget for completion.
2. **Fire-and-forget delivery before persistence**: Reminders are delivered via `Tell` before being marked as completed, so there's no way to "undo" delivery if the completion step fails.
3. **Silent failure on mark-complete**: `MarkRemindersAsCompletedAsync` returns `false` on failure, but the return value is not checked or logged in `ProcessReminders`.
4. **Transactional batch completion**: The SQL implementation marks all reminders as completed in a single transaction. If any part fails (timeout), the entire batch rolls back and *none* of the reminders are marked complete.

## Relevant Code

- `ReminderScheduler.cs` - `ProcessReminders()` method (line ~347)
- `SqlReminderStorage.cs` - `MarkRemindersAsCompletedAsync()` (line ~169)

### PR DESCRIPTION
**Pull request by Aaronontheweb**
## Summary

Fixes #73. When thousands of reminders become due simultaneously (e.g., ~2,000 non-recurring reminders at market open on Azure SQL), `ProcessReminders` enters an infinite re-delivery loop because:

1. A **single `CancellationTokenSource`** with a 5-second timeout was shared across all storage operations (fetch, deliver, mark-complete, reschedule, overview). A slow fetch starves mark-complete.
2. **No fetch limit** — all due reminders loaded in a single unbounded query.
3. **N individual UPDATE round-trips** in `MarkRemindersAsCompletedAsync` — 2,000 reminders = 2,000 sequential UPDATEs in one transaction, consistently exceeding the timeout under DTU pressure.
4. Since delivery is fire-and-forget `Tell` (at-least-once), reminders delivered but not marked complete are re-fetched and re-delivered every tick (~5s) indefinitely.

### Changes

- **Per-phase CTS**: Each storage operation (fetch, mark-complete, retries, recurring, overview) gets its own `CancellationTokenSource(StorageTimeout)` so a slow fetch doesn't starve mark-complete.
- **`MaxBatchSize` setting** (default 1,000): Caps `GetNextRemindersAsync` via `TOP`/`LIMIT` so we process in bounded batches.
- **Batched UPDATE via VALUES JOIN**: `MarkRemindersAsCompletedAsync` now groups completions and uses dialect-specific batched UPDATE statements (500 per chunk to stay within SQL Server's 2,100 parameter limit). Reduces 2,000 round-trips to 4 statements.
- **No transaction wrapper on mark-complete**: Each chunk auto-commits independently. If chunk 4 times out, chunks 1-3 are preserved. Mark-complete is idempotent.
- **Break on mark-complete failure**: Prevents tight-looping against a struggling database. The next timer tick provides natural backoff.
- **Delivered-key tracking**: Within a single `ProcessReminders` call, already-delivered reminders are not re-sent if re-fetched due to a mark-complete failure.

### Benchmark Results (PostgreSQL, batched UPDATE)

| Reminders | BatchSize | Mean | Reminders/sec |
|-----------|-----------|-----:|:-------------:|
| 1,000 | 1,000 | 322ms | 3,107 |
| 1,000 | 5,000 | 305ms | 3,277 |
| 5,000 | 1,000 | 4.5s | 1,102 |
| 5,000 | 5,000 | 1.6s | 3,093 |
| 25,000 | 1,000 | 54.5s | 458 |
| 25,000 | 5,000 | 16.2s | 1,547 |

### Breaking Changes

- `IReminderStorage.GetNextRemindersAsync` adds `int? maxCount = null` parameter. External implementors will need to update. Acceptable pre-1.0.

## Test plan

- [x] All 125 existing tests pass
- [x] New `GetNextReminders_ShouldRespectMaxCount` test validates batching at the storage level
- [x] Benchmarks run against real PostgreSQL via docker-compose
- [ ] Design review needed for failure mode handling (recurring reminder scheduling failure can break the chain)

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
## Benchmark Results

`FetchAndCompleteAllReminders` — measures the full fetch → mark-complete loop against real PostgreSQL (Testcontainers).

```
BenchmarkDotNet v0.14.0, Ubuntu 24.04.3 LTS (Noble Numbat)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK 9.0.304
  [Host]    : .NET 9.0.8 (9.0.825.36511), X64 RyuJIT AVX2
  MediumRun : .NET 9.0.8 (9.0.825.36511), X64 RyuJIT AVX2

Job=MediumRun  InvocationCount=1  IterationCount=5  
LaunchCount=2  RunStrategy=Monitoring  UnrollFactor=1  
WarmupCount=2  
```

| Method                       | ReminderCount | MaxBatchSize | Mean        | Error       | StdDev      | Reminders/sec |
|----------------------------- |-------------- |------------- |------------:|------------:|------------:|--------------:|
| FetchAndCompleteAllReminders | 1000          | 1000         |    338.2 ms |    47.82 ms |    31.63 ms |         2,957 |
| FetchAndCompleteAllReminders | 1000          | 5000         |    337.4 ms |    41.50 ms |    27.45 ms |         2,964 |
| FetchAndCompleteAllReminders | 5000          | 1000         |  3,157.5 ms |   110.38 ms |    73.01 ms |         1,584 |
| FetchAndCompleteAllReminders | 5000          | 5000         |  1,452.0 ms |    86.01 ms |    56.89 ms |         3,443 |
| FetchAndCompleteAllReminders | 25000         | 1000         | 56,923.6 ms | 7,517.12 ms | 4,972.11 ms |           439 |
| FetchAndCompleteAllReminders | 25000         | 5000         | 16,146.0 ms | 1,096.19 ms |   725.06 ms |         1,548 |

### Key Takeaways

- **1K reminders**: ~338ms regardless of batch size (single batch either way). ~2,960 reminders/sec.
- **5K reminders**: `MaxBatchSize=5000` (single batch) is **2.2x faster** than `MaxBatchSize=1000` (5 batches) — 1.45s vs 3.16s. The batched VALUES JOIN UPDATE shines when there's fewer round-trips.
- **25K reminders**: `MaxBatchSize=5000` is **3.5x faster** than `MaxBatchSize=1000` — 16.1s vs 56.9s. At 1K batch size, the 25 round-trips dominate; at 5K, only 5 batches are needed.
- **Throughput scales well**: 5K/5000 achieves 3,443 reminders/sec, matching the 1K throughput. The 25K/1000 case drops to 439/sec due to the overhead of many small batches.

The default `MaxBatchSize=1000` is a conservative choice that stays well within SQL Server's 2,100 parameter limit while still completing 1K reminders in under 400ms. Users processing larger volumes can increase this setting.

**Comment by Aaronontheweb** [comment]
## Reliability hardening update

Implemented and tested the high/medium risk items from review:

- Reworked scheduler batch flow to process fetched reminders in interleaved deliver/persist chunks (`DeliveryCommitChunkSize`, default 100) to bound first-failure duplicate blast radius.
- Added `ReminderSettings.Validate()` and enforce validation (`MaxBatchSize >= 1`, `DeliveryCommitChunkSize >= 1`, positive storage timeout).
- Fixed completion batching behavior by using a single completion timestamp per processed chunk, restoring SQL grouping effectiveness.
- Changed recurring durability semantics to persist next occurrence as the recurring durability boundary; recurring reminders are no longer marked complete in the same path as one-time reminders.
- Removed shared recurring write timeout budget by using per-operation timeout scopes for retries/recurrence scheduling.
- Updated failure mode documentation and README to reflect new behavior and reliability guarantees.
- Added/updated tests for settings validation and blast-radius behavior; switched write-circuit tests to async TestKit patterns.

Validation:
- `dotnet test`: **132 passed, 0 failed**

## Updated benchmark run
Command:
- `dotnet run -c Release --project src/Akka.Reminders.Benchmarks -- --filter *ReminderStorageBenchmarks*`

Results:

| ReminderCount | MaxBatchSize | Mean | Reminders/sec |
|---:|---:|---:|---:|
| 1,000 | 1,000 | 323.9 ms | 3,088 |
| 1,000 | 5,000 | 319.4 ms | 3,131 |
| 5,000 | 1,000 | 3,193.2 ms | 1,566 |
| 5,000 | 5,000 | 1,445.4 ms | 3,459 |
| 25,000 | 1,000 | 57,860.1 ms | 432 |
| 25,000 | 5,000 | 15,124.4 ms | 1,653 |

Benchmark artifacts:
- `BenchmarkDotNet.Artifacts/results/Akka.Reminders.Benchmarks.ReminderStorageBenchmarks-report.csv`
- `BenchmarkDotNet.Artifacts/results/Akka.Reminders.Benchmarks.ReminderStorageBenchmarks-report-github.md`
- `BenchmarkDotNet.Artifacts/results/Akka.Reminders.Benchmarks.ReminderStorageBenchmarks-report.html`

File: src/Akka.Reminders.Benchmarks/Program.cs [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+Console.WriteLine("IMPORTANT: Make sure PostgreSQL is running via 'docker-compose up -d' before running benchmarks.");
+Console.WriteLine();
+
+// Try to connect to PostgreSQL to give early warning
+try
+{
+    await using var conn = new NpgsqlConnection(SqlReminderBenchmarkBase.ConnectionString);
+    await conn.OpenAsync();
+}
+catch (Exception)
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Benchmarks/Program.cs:17]: Borrowed this benchmark + external container design from https://github.com/akkadotnet/Akka.Streams.Kafka - eliminates a ton of garbage from the arrangement of the benchmarks themselves

File: src/Akka.Reminders.Benchmarks/ReminderStorageBenchmarks.cs [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+    [Benchmark(OperationsPerInvoke = 1)]
+    public async Task<int> FetchAndCompleteAllReminders()
+    {
+        var now = DateTimeOffset.UtcNow;
+        var deadline = now.AddMinutes(1);
+        var totalProcessed = 0;
+
+        while (true)
+        {
+            var batch = await Storage.GetNextRemindersAsync(deadline, now, maxCount: MaxBatchSize);
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Benchmarks/ReminderStorageBenchmarks.cs]: Mostly testing reminder storage here, which is the big bottleneck

File: docs/design/failure-modes.md [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+
+### 3. Batched UPDATE via VALUES JOIN
+
+**Problem:** `MarkRemindersAsCompletedAsync` executed N individual UPDATE statements in a single transaction. With 2,000 reminders, that's 2,000 sequential round-trips, consistently exceeding the 5-second timeout on a loaded database.
+
+**Fix:** Groups completions by `(Status, When)`, chunks at 500 per statement (to stay within SQL Server's 2,100 parameter limit), and uses dialect-specific batched UPDATE syntax:
+- **SQL Server:** `UPDATE t ... FROM table t INNER JOIN (VALUES ...) AS v(...) ON ...`
+- **PostgreSQL:** `UPDATE table t SET ... FROM (VALUES ...) AS v(...) WHERE ...`
+
+Each chunk auto-commits independently (no wrapping transaction). If chunk 4 of 5 times out, chunks 1-3 are already persisted. Mark-complete is idempotent, so partial progress is safe.
```
Comment (Aaronontheweb) [inline docs/design/failure-modes.md:71]: Important detail for really large delivery batches

File: docs/design/failure-modes.md [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+
+**Fix:** Each fetched batch is processed in smaller chunks (`DeliveryCommitChunkSize`, default 100). After each chunk is delivered, writes are attempted immediately. If writes fail, processing stops before the next chunk.
+
+This bounds first-failure duplicate blast radius to chunk size instead of full fetch size.
+
+### 6. Recurring durability boundary changed
+
+**Problem:** If mark-complete succeeded for a recurring reminder but scheduling the next occurrence failed, the recurring chain could break permanently.
+
+**Fix:** Recurring reminders are no longer marked complete. Instead, their durability boundary is successful persistence of the next occurrence (idempotent upsert). If scheduling the next occurrence fails, the original reminder remains pending and can be retried on the next tick.
```
Comment (Aaronontheweb) [inline docs/design/failure-modes.md:96]: Another important reliability fix

File: src/Akka.Reminders.Sql/Internal/PostgreSqlDialect.cs [hunk 5]
```diff
@@ -80,17 +80,18 @@ DO UPDATE SET
             """;
     }
 
-    public string GetSelectDueRemindersSql(string schemaName, string tableName)
+    public string GetSelectDueRemindersSql(string schemaName, string tableName, int? maxCount = null)
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Sql/Internal/PostgreSqlDialect.cs]: We should enforce a hard limit by default here - I believe this gets bounds-checked by the upstream settings validator but this is where the real danger lives, so it's good to enforce it here too (and it shouldn't be expensive)

File: src/Akka.Reminders.Sql/Internal/SqlServerDialect.cs [hunk 6]
```diff
@@ -102,12 +102,13 @@ WHEN NOT MATCHED THEN
             """;
     }
 
-    public string GetSelectDueRemindersSql(string schemaName, string tableName)
+    public string GetSelectDueRemindersSql(string schemaName, string tableName, int? maxCount = null)
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Sql/Internal/SqlServerDialect.cs]: Same as my comment with the postgres stuff. We should just use a value object for this that enforces `>1` and make it a mandatory parameter.

File: src/Akka.Reminders.Sql/SqlReminderStorage.cs [hunk 7]
```diff
@@ -99,6 +99,7 @@ private static DateTimeOffset TruncateToMicroseconds(DateTimeOffset dto)
     public async Task<PendingRemindersWithSummary> GetNextRemindersAsync(
         DateTimeOffset untilDeadline,
         DateTimeOffset now,
+        int? maxCount = null,
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Sql/SqlReminderStorage.cs]: Need to enforce this with the value object I mentioned earlier too

File: src/Akka.Reminders.Sql/SqlReminderStorage.cs [hunk 8]
```diff
@@ -166,6 +167,11 @@ public async Task<PendingRemindersWithSummary> GetNextRemindersAsync(
         return new PendingRemindersWithSummary(reminders, adjustedOverview);
     }
 
+    // SQL Server has a limit of 2100 parameters per query.
+    // With 3 parameters per reminder (sr, eid, rk) + 2 shared (completedAtUtc, status),
+    // we can safely fit ~690 reminders per batch statement. Use 500 to leave headroom.
+    private const int MaxRemindersPerStatement = 500;
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Sql/SqlReminderStorage.cs:176]: LGTM

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs [hunk 9]
```diff
@@ -0,0 +1,161 @@
...
+        _resolver.RegisterShardRegion("test-region", testProbe);
+        var testScheduler = (TestScheduler)Sys.Scheduler;
+        var now = testScheduler.Now;
+
+        for (var i = 0; i < 5; i++)
+        {
+            await _innerStorage.ScheduleReminderAsync(new ScheduledReminder(
+                new ReminderEntity("test-region", $"entity-{i}"),
+                new ReminderKey($"reminder-{i}"),
+                now.AddSeconds(-1),
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:82]: scheduled in the past - not sure we should support that but ok

Comment (Aaronontheweb) [reply src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:82]: I guess it's fine?

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs [hunk 10]
```diff
@@ -0,0 +1,161 @@
...
+        var scheduler = CreateScheduler(maxBatchSize: 1000);
+        await WaitForSchedulerReady(scheduler);
+
+        // Tick 1: all 5 delivered before mark-complete fails → circuit opens
+        testScheduler.Advance(TimeSpan.FromMilliseconds(100));
+        var firstTickMessages = await CollectMessages(testProbe, 5, TimeSpan.FromSeconds(5));
+        Assert.Equal(5, firstTickMessages.Count);
+
+        // Write failure should stop further chunk processing during this run.
+        await testProbe.ExpectNoMsgAsync(TimeSpan.FromMilliseconds(500));
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:109]: This doesn't actually test anything definitive, because there's no additional reminders to be fired - this would appear to work regardless of whether or not the storage succeeded. Needs to be hardened so we can observe the failure-handling more visibly.

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs [hunk 11]
```diff
@@ -0,0 +1,161 @@
...
+
+        var scheduler = CreateScheduler(maxBatchSize: 1000);
+        await WaitForSchedulerReady(scheduler);
+        testScheduler.Advance(TimeSpan.FromSeconds(6));
+
+        var messages = await CollectMessages(testProbe, 3, TimeSpan.FromSeconds(5));
+        Assert.Equal(3, messages.Count);
+
+        testScheduler.Advance(TimeSpan.FromSeconds(5));
+        await testProbe.ExpectNoMsgAsync(TimeSpan.FromMilliseconds(500));
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:130]: Same issue as the previous comment

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs [hunk 12]
```diff
@@ -0,0 +1,161 @@
...
+        }
+
+        _storage.FailWrites = true;
+        var scheduler = CreateScheduler(maxBatchSize: 1000, deliveryCommitChunkSize: 3);
+        await WaitForSchedulerReady(scheduler);
+        testScheduler.Advance(TimeSpan.FromMilliseconds(100));
+
+        // First failed tick should be bounded by DeliveryCommitChunkSize.
+        await CollectMessages(testProbe, 3, TimeSpan.FromSeconds(5));
+        await testProbe.ExpectNoMsgAsync(TimeSpan.FromMilliseconds(300));
```
Comment (Aaronontheweb) [inline src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:150]: This is more like it - first test that can visibly demonstrate the "stopping" when the circuit breaker is open. We should also demonstrate the circuit breaker closing again (in a new test) and resuming deliveries once db connectivity gets restored.

File: src/Akka.Reminders/Storage/InMemoryReminderStorage.cs [hunk 13]
```diff
@@ -134,22 +134,28 @@ public Task<ReminderOverview> GetRemindersOverviewAsync(DateTimeOffset now, Canc
     public Task<PendingRemindersWithSummary> GetNextRemindersAsync(
         DateTimeOffset untilDeadline,
         DateTimeOffset now,
+        int? maxCount = null,
```
Comment (Aaronontheweb) [inline src/Akka.Reminders/Storage/InMemoryReminderStorage.cs]: For consistency, this should also be hardened like the SQL specs

**Review by Aaronontheweb — COMMENTED** [review]
Partial review - not done yet

File: src/Akka.Reminders/ReminderScheduler.cs [hunk 14]
```diff
@@ -40,6 +52,20 @@ public sealed record ReminderSettings
     /// Actual delay = RetryBackoffBase * (2 ^ attemptCount)
     /// </summary>
     public TimeSpan RetryBackoffBase { get; init; } = TimeSpan.FromSeconds(30);
+
+    /// <summary>
+    /// Validates reminder settings.
+    /// </summary>
+    public void Validate()
```
Comment (Aaronontheweb) [inline src/Akka.Reminders/ReminderScheduler.cs:59]: LGTM

File: src/Akka.Reminders/ReminderScheduler.cs [hunk 15]
```diff
@@ -346,95 +381,241 @@ private Task LoadReminderOverview()
...
+        // the blast radius to at most 1 duplicate delivery during the probe.
+        var effectiveBatchSize = _writeCircuitOpen ? 1 : Settings.MaxBatchSize;
 
-        var completedReminders = new List<CompletedReminder>();
-        var recurringRemindersToSchedule = new List<ScheduledReminder>();
-        var failedRemindersToRetry = new List<ScheduledReminder>();
-        var permanentlyFailedReminders = new List<CompletedReminder>();
+        if (_writeCircuitOpen)
+        {
+            _log.Warning("Write circuit is open — probing with a single reminder before resuming");
```
Comment (Aaronontheweb) [inline src/Akka.Reminders/ReminderScheduler.cs:396]: ..... but do we actually probe with a single reminder? seems like we just kind of plow ahead?

File: src/Akka.Reminders/ReminderScheduler.cs [hunk 16]
```diff
@@ -346,95 +381,241 @@ private Task LoadReminderOverview()
...
-                    reminder, reminder.AttemptCount + 1, Settings.MaxDeliveryAttempts);
+                using var fetchCts = new CancellationTokenSource(Settings.StorageTimeout);
+                batch = await Storage.GetNextRemindersAsync(untilDeadline, TimeProvider.Now,
+                    effectiveBatchSize, fetchCts.Token);
+                _log.Info("Fetched {0} due reminders (batch)", batch.Reminders.Count);
+            }
+            catch (Exception ex)
+            {
+                _log.Error(ex, "Failed to fetch due reminders from storage");
+                break;
```
Comment (Aaronontheweb) [inline src/Akka.Reminders/ReminderScheduler.cs:416]: We don't trigger any circuit-breaker activity here because no reminders were fired, correct? we should explicitly mention this with a comment

**Review by Aaronontheweb — COMMENTED** [review]
Left some more comments

File: src/Akka.Reminders.Benchmarks/Program.cs (hunk 1 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Benchmarks/Program.cs:17]: Yes, this benchmark setup was intentionally borrowed from Akka.Streams.Kafka to keep benchmark arrangement overhead low.

File: src/Akka.Reminders.Benchmarks/ReminderStorageBenchmarks.cs (hunk 2 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Benchmarks/ReminderStorageBenchmarks.cs]: Correct, this benchmark intentionally isolates reminder storage fetch and complete performance because that is the dominant bottleneck.

File: docs/design/failure-modes.md (hunk 3 above)
Comment (Aaronontheweb) [reply docs/design/failure-modes.md:71]: Agreed, this large-batch chunk commit detail is retained in the failure modes documentation.

File: docs/design/failure-modes.md (hunk 4 above)
Comment (Aaronontheweb) [reply docs/design/failure-modes.md:96]: Agreed, recurring durability now hinges on persisting the next occurrence rather than marking the current one complete.

File: src/Akka.Reminders.Sql/Internal/PostgreSqlDialect.cs (hunk 5 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Sql/Internal/PostgreSqlDialect.cs]: Addressed: fetch size is now mandatory via ReminderBatchSize and the PostgreSQL dialect also guards maxCount >= 1.

File: src/Akka.Reminders.Sql/Internal/SqlServerDialect.cs (hunk 6 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Sql/Internal/SqlServerDialect.cs]: Addressed: switched to a mandatory ReminderBatchSize value object and SQL Server dialect enforces maxCount >= 1.

File: src/Akka.Reminders.Sql/SqlReminderStorage.cs (hunk 7 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Sql/SqlReminderStorage.cs]: Addressed: SqlReminderStorage.GetNextRemindersAsync now requires ReminderBatchSize, so unbounded fetches are not allowed.

File: src/Akka.Reminders.Sql/SqlReminderStorage.cs (hunk 8 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Sql/SqlReminderStorage.cs:176]: Thanks.

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs (hunk 9 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:82]: Kept this behavior in tests intentionally, overdue scheduling gives deterministic immediate processing coverage.

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs (hunk 10 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:109]: Addressed: tests now assert observable stop behavior and first-failure blast-radius bounds.

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs (hunk 11 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:130]: Addressed together with the previous thread by strengthening the write-outage test assertions.

File: src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs (hunk 12 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders.Tests/WriteCircuitBreakerSpecs.cs:150]: Addressed: added a recovery test that demonstrates circuit close and resumption of full-batch processing after writes recover.

File: src/Akka.Reminders/Storage/InMemoryReminderStorage.cs (hunk 13 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders/Storage/InMemoryReminderStorage.cs]: Addressed: InMemoryReminderStorage now also uses mandatory ReminderBatchSize and always applies a bounded Take.

File: src/Akka.Reminders/ReminderScheduler.cs (hunk 14 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders/ReminderScheduler.cs:59]: Thanks.

File: src/Akka.Reminders/ReminderScheduler.cs (hunk 15 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders/ReminderScheduler.cs:396]: Addressed with stronger specs: while open, probing uses a single reminder; recovery path behavior is now explicitly tested.

File: src/Akka.Reminders/ReminderScheduler.cs (hunk 16 above)
Comment (Aaronontheweb) [reply src/Akka.Reminders/ReminderScheduler.cs:416]: Added explicit comment in fetch failure path clarifying that no write-circuit transition occurs when no reminders are delivered.
